version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      # - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/
      # - ~/.docker-conf/rabbitmq/log/:/var/log/rabbitmq
      - /var/lib/rabbitmq
    env_file:
      - .env

  app:
    container_name: ttf-app
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      # - database
      - rabbitmq
    ports:
      - 3800:3800
    environment:
      NODE_ENV: development
      PORT: 3800
      # DATABASE_URL: postgres://postgres:postgres@host.docker.internal:3802/main
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_USER: user
      RABBITMQ_PASS: password
      RABBITMQ_HOST: rabbitmq:5672
    restart: unless-stopped
    links:
      # - database
      - rabbitmq
    volumes:
      - ./src:/usr/src/app/src
    command: yarn run start:dev

  # database:
  #   image: postgres:14.1-alpine
  #   restart: unless-stopped
  #   environment:
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   ports:
  #     - '3802:5432'
  #   volumes:
  #     - db:/var/lib/postgresql/data
  #     - ./db/init.sql:/docker-entrypoint-initdb.d/create_tables.sql

volumes:
  db:
    driver: local
  rabbitmq:
    driver: local

networks:
  default:
